# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Configuration for MkDocs
mkdocs:
  configuration: mkdocs.yml

# Python dependencies
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
