version: 2

build:
  os: ubuntu-22.04
  jobs:
    pre_build:
      - "python docs/scripts/generate_issue_list.py"
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
