site_name: local-data-platform
site_author: Local Data Platform core team
copyright: 2024, Local Data Platform core team

repo_url: https://github.com/tusharchou/local-data-platform
repo_name: local-data-platform

nav:
  - Home: index.md
  - Wiki:
      - Contents: wiki/CONTENTS
      - Project Overview: wiki/PROJECT_OVERVIEW
      - Problem Statement: wiki/PROBLEM_STATEMENT
      - Technical Specifications: wiki/TECHNICAL_SPECIFICATIONS
      - Development & Documentation: wiki/DEVELOPMENT
      - Project Structure: wiki/PROJECT_STRUCTURE
      - Recipes & Examples: wiki/RECIPES
      - Contributing: wiki/CONTRIBUTING
      - Branches: wiki/BRANCHES
      - Active Docs URLs: wiki/ACTIVE_DOCS_URLS
  - User Guide:
      - Recipes: recipes.md
  - API Reference: api.md
  - Contributing: 
      - User Issues: user_issues.md
      - Feature Requests: developer_feature_requests.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: docs

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: [src]
            docstring_style: google
            members_order: source
            show_source: true
            filters:
              - "!^local_data_platform\\.real_world_use_cases"