site_name: local-data-platform
site_author: Local Data Platform core team
copyright: 2024, Local Data Platform core team

repo_url: https://github.com/tusharchou/local-data-platform
repo_name: local-data-platform

nav:
  - Home: index.md
  - "About LDP": wiki/VISION.md
  - Business Solution: 
      - Business Problem: wiki/business/PROPOSAL.md
      - Marketing Data Analysis: wiki/business/MARKETING_DATA_ANALYSIS.md
      - "Photo Management": wiki/usecases/PHOTO_MANAGEMENT.md
  - "Conceptual Workflow":
      - "Photo Management": wiki/workflow/PHOTO_MANAGEMENT.md
  - Features:
      - Library:
          - "Base": wiki/library/BASE.md
          - "Exceptions": wiki/library/EXCEPTION.md
          - "Test": wiki/library/TEST.md
      - Development:
          - "Github": wiki/GITHUB.md

  - Contribute Now: 
      - "How To Contribute": wiki/plan/ISSUES.md
  - Project Wiki:
      - Overview: wiki/PROJECT_OVERVIEW.md
      - Problem Statement: wiki/PROBLEM_STATEMENT.md
      - Technical Specs: wiki/TECHNICAL_SPECIFICATIONS.md
      - Project Structure: wiki/PROJECT_STRUCTURE.md
      - Development Process: wiki/DEVELOPMENT.md


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: docs

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - autorefs
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: [src]
            docstring_style: google
            members_order: source
            show_source: true
            filters:
              - "!^local_data_platform\\.real_world_use_cases"