site_name: local-data-platform
site_author: Local Data Platform core team
copyright: 2024, Local Data Platform core team

repo_url: https://github.com/tusharchou/local-data-platform
repo_name: local-data-platform

nav:
  - Home: index.md
  - Recipes: recipes.md
  - API Reference: api.md
  - Contributing: 
      - "How to Contribute": contributing.md
      - User Issues: user_issues.md
      - Feature Requests: developer_feature_requests.md
      - PR Reviews: pr_reviews.md
      - PR History: PR_HISTORY.md
      - Dev Tooling Update: developer_tooling_update.md
  - Project Wiki:
      - Overview: wiki/PROJECT_OVERVIEW.md
      - Problem Statement: wiki/PROBLEM_STATEMENT.md
      - Technical Specs: wiki/TECHNICAL_SPECIFICATIONS.md
      - Project Structure: wiki/PROJECT_STRUCTURE.md
      - Development Process: wiki/DEVELOPMENT.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: docs

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: [src]
            docstring_style: google
            members_order: source
            show_source: true
            filters:
              - "!^local_data_platform\\.real_world_use_cases"