"""
local-data-platform : the open-source Python library for data storage on your local device

How to create a data store with local_data_platform in 3 seconds:

1. Write a json configuration
    {
        "from": "NEAR_Coin"
        "to": "Local"
        "question": "Growth?"
        "impact": "Investment"
    }
2. Run the python script
    > python is_near_a_good_investment.py
3. See the data and share the analysis with autogenerated Streamlit app
    > ldp show my portfolio

"""