name: CI - Lint, Test, and Docs

on:
  pull_request:
    branches: [ main, fix-readthedocs, docs-sidebar-recipes-from-fix-readthedocs ]
  push:
    branches: [ main, fix-readthedocs, docs-sidebar-recipes-from-fix-readthedocs ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r docs/requirements.txt || true
          pip install -e . || true
      - name: Lint with flake8
        run: |
          flake8 local-data-platform/ tests/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt || true
          pip install -e . || true
          pip install pytest
      - name: Run tests
        run: |
          pytest tests/

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -e . || true
      - name: Build documentation
        run: |
          cd docs
          make html

# Only allow merge if all jobs succeed (enforced by branch protection rules in GitHub settings)
