name: CI - Lint, Test, and Docs

on:
  pull_request:
    branches: [ main, fix-readthedocs, docs-sidebar-recipes-from-fix-readthedocs ]
  push:
    branches: [ main, fix-readthedocs, docs-sidebar-recipes-from-fix-readthedocs ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: make install
      - name: Lint with flake8
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: make install
      - name: Build documentation
        run: make docs

# Only allow merge if all jobs succeed (enforced by branch protection rules in GitHub settings)
